"""SQLite-backed state store.

Keeps:

* ``dockets`` — per-docket high-water mark for the docket-level short-circuit
  plus cached metadata (court_id, case_name, docket_number, absolute_url) for
  description rendering at emit time.
* ``courts`` — citation_string + name lookup per court_id, fetched once.
* ``entries`` — every docket entry we've already processed, with a content
  fingerprint. Used for dedup and the docket-level high-water mark.
* ``hearings`` — the canonical "logical" hearings per case. Each hearing has a
  stable ``hearing_key`` (chosen by the LLM) so reschedules and dial-in info
  updates land on the same row.
* ``deadlines`` — per-case filing deadlines (response/reply/brief due dates).
  Same shape as hearings: stable ``deadline_key`` per logical deadline, so
  granted extensions land on the same row rather than creating duplicates.
* ``case_summaries`` — opt-in per-docket prose summary ("what is this case
  about, who's involved, where does it stand") rendered into the index page.
  Generated by a separate higher-tier LLM pass over each docket's operative
  pleading + judgment if any; kept independent of the per-entry extractor
  so the cheaper extraction pipeline isn't affected.
* ``webhook_events`` — Idempotency-Key dedup for the webhook receiver.
"""

from __future__ import annotations

import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Iterator, Optional

SCHEMA = """
CREATE TABLE IF NOT EXISTS dockets (
    docket_id INTEGER PRIMARY KEY,
    date_modified TEXT,
    last_synced_at TEXT NOT NULL,
    court_id TEXT,
    docket_number TEXT,
    case_name TEXT,
    absolute_url TEXT
);

CREATE TABLE IF NOT EXISTS courts (
    court_id TEXT PRIMARY KEY,
    citation_string TEXT,
    short_name TEXT,
    full_name TEXT,
    fetched_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS entries (
    docket_id INTEGER NOT NULL,
    entry_id INTEGER NOT NULL,
    entry_number INTEGER,        -- docket-position number (PACER's "[65]")
    date_filed TEXT,
    date_modified TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    description TEXT,            -- raw entry text; used to resolve cross-refs
    short_description TEXT,
    recap_documents TEXT,        -- JSON list of attached docs; surfaced as URLs in event description
    processed_at TEXT NOT NULL,
    PRIMARY KEY (docket_id, entry_id)
);

CREATE TABLE IF NOT EXISTS hearings (
    case_id TEXT NOT NULL,
    hearing_key TEXT NOT NULL,
    title TEXT NOT NULL,
    starts_at_utc TEXT,
    duration_minutes INTEGER,
    timezone TEXT NOT NULL,
    location TEXT,
    judge TEXT,
    notes TEXT,
    dial_in TEXT,
    status TEXT NOT NULL,        -- scheduled | held | cancelled | unknown
    significance TEXT,           -- "major" (default) | "minor" — calendar filter
    gcal_event_id TEXT,
    m365_event_id TEXT,
    docket_id INTEGER,           -- docket whose entry most recently updated this hearing
    source_entry_ids TEXT NOT NULL, -- JSON list of entry IDs
    last_updated TEXT NOT NULL,
    PRIMARY KEY (case_id, hearing_key)
);

CREATE TABLE IF NOT EXISTS deadlines (
    case_id TEXT NOT NULL,
    deadline_key TEXT NOT NULL,
    title TEXT NOT NULL,
    due_at_utc TEXT,              -- UTC ISO; renderer converts to court-local
    timezone TEXT NOT NULL,       -- IANA tz of the court the deadline was set in
    notes TEXT,
    status TEXT NOT NULL,         -- pending | passed | met | cancelled | unknown
    significance TEXT,            -- "major" (default) | "minor" — calendar filter
    deadline_type TEXT,           -- response | reply | brief | other (informational)
    gcal_event_id TEXT,
    m365_event_id TEXT,
    docket_id INTEGER,            -- docket whose entry most recently updated this row
    source_entry_ids TEXT NOT NULL, -- JSON list of entry IDs
    last_updated TEXT NOT NULL,
    PRIMARY KEY (case_id, deadline_key)
);

CREATE TABLE IF NOT EXISTS case_summaries (
    case_id TEXT NOT NULL,
    docket_id INTEGER NOT NULL,
    summary TEXT NOT NULL,
    model TEXT,
    source_entry_ids TEXT,         -- JSON list of CL entry IDs fed to the LLM
    stale INTEGER NOT NULL DEFAULT 0,  -- 1 when sync saw a new operative pleading or disposition that may invalidate the prose
    stale_since TEXT,              -- ISO timestamp of the most recent stale-flagging entry; used by the webhook debounce so a burst of PACER uploads coalesces into one regeneration
    generated_at TEXT NOT NULL,
    PRIMARY KEY (case_id, docket_id)
);

CREATE TABLE IF NOT EXISTS webhook_events (
    -- CourtListener sends an Idempotency-Key (UUID) header on every webhook
    -- delivery. We store seen keys so retries are no-ops.
    idempotency_key TEXT PRIMARY KEY,
    event_type INTEGER,
    received_at TEXT NOT NULL
);
"""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class Store:
    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        # check_same_thread=False so the webhook server (ThreadingHTTPServer)
        # can use this connection from worker threads. We serialize callers
        # explicitly — see WebhookServer.process_locked.
        self.conn = sqlite3.connect(self.path, check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        self.conn.executescript(SCHEMA)
        self._migrate()
        self.conn.commit()

    def _migrate(self) -> None:
        """Idempotent ALTER TABLE for columns added after first release."""
        for table, col, type_ in [
            ("dockets", "court_id", "TEXT"),
            ("dockets", "docket_number", "TEXT"),
            ("dockets", "case_name", "TEXT"),
            ("dockets", "absolute_url", "TEXT"),
            ("hearings", "docket_id", "INTEGER"),
            ("hearings", "significance", "TEXT"),
            ("entries", "date_filed", "TEXT"),
            ("entries", "entry_number", "INTEGER"),
            ("entries", "description", "TEXT"),
            ("entries", "short_description", "TEXT"),
            ("entries", "recap_documents", "TEXT"),
            ("hearings", "m365_event_id", "TEXT"),
            ("deadlines", "m365_event_id", "TEXT"),
            ("case_summaries", "stale", "INTEGER NOT NULL DEFAULT 0"),
            ("case_summaries", "stale_since", "TEXT"),
        ]:
            try:
                self.conn.execute(f"ALTER TABLE {table} ADD COLUMN {col} {type_}")
            except sqlite3.OperationalError:
                pass  # column already exists
        # Drop columns that older releases populated for description rendering.
        # Renderer no longer reads them; storing them was wasted IO and disk.
        for col in ("description_text", "pdf_text_excerpt"):
            try:
                self.conn.execute(f"ALTER TABLE entries DROP COLUMN {col}")
            except sqlite3.OperationalError:
                pass  # column doesn't exist (fresh DB)
        # Index lives in _migrate (not SCHEMA) because it depends on a column
        # added by ALTER TABLE above; running it from SCHEMA on an old DB
        # would reference entry_number before the migration creates it.
        self.conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_entries_docket_entry_number "
            "ON entries (docket_id, entry_number)"
        )

    def close(self) -> None:
        self.conn.close()

    @contextmanager
    def tx(self) -> Iterator[sqlite3.Connection]:
        try:
            yield self.conn
            self.conn.commit()
        except Exception:
            self.conn.rollback()
            raise

    # --- dockets ---

    def docket_last_modified(self, docket_id: int) -> Optional[str]:
        row = self.conn.execute(
            "SELECT date_modified FROM dockets WHERE docket_id=?",
            (docket_id,),
        ).fetchone()
        return row["date_modified"] if row else None

    def set_docket_last_modified(self, docket_id: int, date_modified: str) -> None:
        # Preserves any metadata columns set by upsert_docket_meta.
        self.conn.execute(
            """
            INSERT INTO dockets (docket_id, date_modified, last_synced_at)
            VALUES (?, ?, ?)
            ON CONFLICT(docket_id) DO UPDATE SET
              date_modified=excluded.date_modified,
              last_synced_at=excluded.last_synced_at
            """,
            (docket_id, date_modified, _now()),
        )

    def bump_docket_last_modified(self, docket_id: int, candidate: str) -> None:
        """Advance ``dockets.date_modified`` only if ``candidate`` is newer.

        The polling path sets ``date_modified`` to the parent docket's
        authoritative value at the end of each sync_case loop. The webhook
        path never sees the parent docket on each delivery, so the docket
        row's ``date_modified`` would stay frozen at the last poll-time
        value (or NULL for webhook-only deployments). ``activity_date`` on
        the index page is derived from this column, so without this bump
        the index would show a stale "last updated" timestamp even though
        new entries were just processed.

        Done as a conditional UPDATE so concurrent webhook deliveries
        can't race the value backwards.
        """
        self.conn.execute(
            """
            INSERT INTO dockets (docket_id, date_modified, last_synced_at)
            VALUES (?, ?, ?)
            ON CONFLICT(docket_id) DO UPDATE SET
              date_modified=excluded.date_modified,
              last_synced_at=excluded.last_synced_at
              WHERE dockets.date_modified IS NULL
                 OR dockets.date_modified < excluded.date_modified
            """,
            (docket_id, candidate, _now()),
        )

    def upsert_docket_meta(self, docket_id: int, meta: dict[str, Any]) -> None:
        """Cache the human-readable docket metadata we display in event bodies."""
        self.conn.execute(
            """
            INSERT INTO dockets
              (docket_id, last_synced_at, court_id, docket_number, case_name, absolute_url)
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(docket_id) DO UPDATE SET
              court_id=excluded.court_id,
              docket_number=excluded.docket_number,
              case_name=excluded.case_name,
              absolute_url=excluded.absolute_url
            """,
            (
                docket_id,
                _now(),
                meta.get("court_id"),
                meta.get("docket_number"),
                meta.get("case_name"),
                meta.get("absolute_url"),
            ),
        )

    def get_docket_meta(self, docket_id: int) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT court_id, docket_number, case_name, absolute_url "
            "FROM dockets WHERE docket_id=?",
            (docket_id,),
        ).fetchone()
        return dict(row) if row else None

    # --- courts ---

    def get_court_citation(self, court_id: str) -> Optional[str]:
        row = self.conn.execute(
            "SELECT citation_string FROM courts WHERE court_id=?",
            (court_id,),
        ).fetchone()
        return row["citation_string"] if row else None

    def upsert_court(
        self,
        court_id: str,
        citation_string: Optional[str],
        short_name: Optional[str],
        full_name: Optional[str],
    ) -> None:
        self.conn.execute(
            "INSERT OR REPLACE INTO courts "
            "(court_id, citation_string, short_name, full_name, fetched_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (court_id, citation_string, short_name, full_name, _now()),
        )

    # --- entries ---

    def entry_seen(self, docket_id: int, entry_id: int, fingerprint: str) -> bool:
        row = self.conn.execute(
            "SELECT fingerprint FROM entries WHERE docket_id=? AND entry_id=?",
            (docket_id, entry_id),
        ).fetchone()
        return row is not None and row["fingerprint"] == fingerprint

    def mark_entry(
        self,
        docket_id: int,
        entry_id: int,
        date_modified: str,
        fingerprint: str,
        *,
        date_filed: Optional[str] = None,
        entry_number: Optional[int] = None,
        description: Optional[str] = None,
        short_description: Optional[str] = None,
        recap_documents: Optional[list[dict[str, Any]]] = None,
    ) -> None:
        # Always overwrite recap_documents — adding/removing docs is exactly
        # the change we want to surface in the calendar. Pass None to leave
        # the existing JSON untouched (filter-failed entries don't supply it).
        docs_json = json.dumps(recap_documents) if recap_documents is not None else None
        self.conn.execute(
            """
            INSERT INTO entries
              (docket_id, entry_id, entry_number, date_filed, date_modified,
               fingerprint, description, short_description, recap_documents,
               processed_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(docket_id, entry_id) DO UPDATE SET
              entry_number=COALESCE(excluded.entry_number, entries.entry_number),
              date_filed=COALESCE(excluded.date_filed, entries.date_filed),
              date_modified=excluded.date_modified,
              fingerprint=excluded.fingerprint,
              description=COALESCE(excluded.description, entries.description),
              short_description=COALESCE(
                  excluded.short_description, entries.short_description
              ),
              recap_documents=COALESCE(
                  excluded.recap_documents, entries.recap_documents
              ),
              processed_at=excluded.processed_at
            """,
            (
                docket_id,
                entry_id,
                entry_number,
                date_filed,
                date_modified,
                fingerprint,
                description,
                short_description,
                docs_json,
                _now(),
            ),
        )

    def get_entry_by_number(
        self, docket_id: int, entry_number: int
    ) -> Optional[dict[str, Any]]:
        """Look up a docket entry by its position number (PACER's "[65]").

        Returns the stored description / short_description so callers can
        resolve cross-references like "ORDER granting 65 Motion ..." without
        a CL round-trip. Older entries (pre-migration) won't have description
        stored — we return whatever is there.
        """
        row = self.conn.execute(
            "SELECT entry_id, entry_number, date_filed, description, short_description "
            "FROM entries WHERE docket_id=? AND entry_number=?",
            (docket_id, entry_number),
        ).fetchone()
        return dict(row) if row else None

    def get_recent_relevant_entries(
        self, docket_id: int, before_date_modified: str, limit: int = 5
    ) -> list[dict[str, Any]]:
        """Return the last `limit` hearing-relevant entries that came before
        the given timestamp on the docket, newest first.

        "Hearing-relevant" is detected by ``description IS NOT NULL`` — we
        only persist description for entries that passed the regex pre-filter
        in the sync pipeline (filter-failed entries are stored as fingerprint
        stubs with NULL description). This gives the LLM context on what
        recently happened on the docket so it can name a hearing correctly
        even when the entry that sets it (e.g. "PAPERLESS Order Setting
        Telephonic Pretrial Conference") doesn't itself name the underlying
        motion's subject — the answer often lives in a recent motion that
        the order doesn't cite by docket position.
        """
        rows = self.conn.execute(
            """
            SELECT entry_id, entry_number, date_filed, description, short_description
            FROM entries
            WHERE docket_id=? AND date_modified < ? AND description IS NOT NULL
            ORDER BY date_modified DESC LIMIT ?
            """,
            (docket_id, before_date_modified, limit),
        ).fetchall()
        return [dict(r) for r in rows]

    def get_entry_numbers(
        self, entry_ids: Iterable[int]
    ) -> dict[int, int]:
        """Return ``entry_id -> entry_number`` for known entries.

        Used by emit-time description rendering to surface PACER docket
        positions (the "[65]" subscribers see in the CL UI) alongside the
        opaque CourtListener entry IDs. Entries with NULL entry_number
        (rare — pre-migration rows) and unknown ids are omitted.
        """
        ids = [int(i) for i in entry_ids]
        if not ids:
            return {}
        placeholders = ",".join("?" * len(ids))
        rows = self.conn.execute(
            f"SELECT entry_id, entry_number FROM entries "
            f"WHERE entry_id IN ({placeholders}) "
            f"AND entry_number IS NOT NULL",
            ids,
        ).fetchall()
        return {r["entry_id"]: r["entry_number"] for r in rows}

    def get_entry_documents(
        self, entry_ids: Iterable[int]
    ) -> dict[int, list[dict[str, Any]]]:
        """Return ``entry_id -> [recap_document, ...]`` for known entries.

        Each list element is the compact JSON we persist on the entry row
        (id, document_number, attachment_number, description, status flags,
        filepath_ia, filepath_local). Used by emit-time description rendering
        to surface clickable document URLs next to each source entry. Entries
        with NULL recap_documents (pre-migration rows, or filter-failed
        stubs) and unknown ids are omitted.
        """
        ids = [int(i) for i in entry_ids]
        if not ids:
            return {}
        placeholders = ",".join("?" * len(ids))
        rows = self.conn.execute(
            f"SELECT entry_id, recap_documents FROM entries "
            f"WHERE entry_id IN ({placeholders}) "
            f"AND recap_documents IS NOT NULL",
            ids,
        ).fetchall()
        out: dict[int, list[dict[str, Any]]] = {}
        for r in rows:
            try:
                out[r["entry_id"]] = json.loads(r["recap_documents"]) or []
            except (TypeError, ValueError):
                continue
        return out

    def latest_entry_modified(self, docket_id: int) -> Optional[str]:
        row = self.conn.execute(
            "SELECT MAX(date_modified) AS m FROM entries WHERE docket_id=?",
            (docket_id,),
        ).fetchone()
        return row["m"] if row and row["m"] else None

    def get_case_aggregates(
        self, docket_ids: Iterable[int]
    ) -> dict[str, Optional[str]]:
        """Return ``{"date_filed": ..., "activity_date": ...}`` across a case's dockets.

        ``date_filed`` = MIN(entries.date_filed) — the first filed entry on
        any of the case's dockets is the closest stand-in for the case's
        filing date (we don't store the docket-level date_filed CL exposes,
        so this is the cheap derived value). ``activity_date`` = MAX of the
        per-docket date_modified high-water marks, which is what the
        docket-level short-circuit already maintains.

        Either value may be None when no rows are present yet.
        """
        ids = [int(i) for i in docket_ids]
        if not ids:
            return {"date_filed": None, "activity_date": None}
        placeholders = ",".join("?" * len(ids))
        df = self.conn.execute(
            f"SELECT MIN(date_filed) AS d FROM entries "
            f"WHERE docket_id IN ({placeholders}) AND date_filed IS NOT NULL",
            ids,
        ).fetchone()
        am = self.conn.execute(
            f"SELECT MAX(date_modified) AS d FROM dockets "
            f"WHERE docket_id IN ({placeholders}) AND date_modified IS NOT NULL",
            ids,
        ).fetchone()
        return {
            "date_filed": df["d"] if df and df["d"] else None,
            "activity_date": am["d"] if am and am["d"] else None,
        }

    # --- hearings ---

    def get_hearings(self, case_id: str) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM hearings WHERE case_id=?", (case_id,)
        ).fetchall()
        return [self._row_to_hearing(r) for r in rows]

    def get_hearing(self, case_id: str, hearing_key: str) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT * FROM hearings WHERE case_id=? AND hearing_key=?",
            (case_id, hearing_key),
        ).fetchone()
        return self._row_to_hearing(row) if row else None

    def upsert_hearing(self, h: dict[str, Any]) -> None:
        self.conn.execute(
            """
            INSERT INTO hearings
            (case_id, hearing_key, title, starts_at_utc, duration_minutes, timezone,
             location, judge, notes, dial_in, status, significance, gcal_event_id,
             docket_id, source_entry_ids, last_updated)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(case_id, hearing_key) DO UPDATE SET
              title=excluded.title,
              starts_at_utc=excluded.starts_at_utc,
              duration_minutes=excluded.duration_minutes,
              timezone=excluded.timezone,
              location=excluded.location,
              judge=excluded.judge,
              notes=excluded.notes,
              dial_in=excluded.dial_in,
              status=excluded.status,
              significance=COALESCE(excluded.significance, hearings.significance),
              gcal_event_id=COALESCE(excluded.gcal_event_id, hearings.gcal_event_id),
              docket_id=COALESCE(excluded.docket_id, hearings.docket_id),
              source_entry_ids=excluded.source_entry_ids,
              last_updated=excluded.last_updated
            """,
            (
                h["case_id"],
                h["hearing_key"],
                h["title"],
                h.get("starts_at_utc"),
                h.get("duration_minutes"),
                h["timezone"],
                h.get("location"),
                h.get("judge"),
                h.get("notes"),
                h.get("dial_in"),
                h["status"],
                h.get("significance"),
                h.get("gcal_event_id"),
                h.get("docket_id"),
                json.dumps(h.get("source_entry_ids", [])),
                _now(),
            ),
        )

    def set_gcal_id(self, case_id: str, hearing_key: str, gcal_event_id: str) -> None:
        self.conn.execute(
            "UPDATE hearings SET gcal_event_id=? WHERE case_id=? AND hearing_key=?",
            (gcal_event_id, case_id, hearing_key),
        )

    def set_m365_id_for_hearing(
        self, case_id: str, hearing_key: str, m365_event_id: Optional[str],
    ) -> None:
        """Cache (or clear) the Graph-assigned event id for a hearing.

        Graph generates ids server-side, so we persist them after first
        create to avoid a $filter lookup on every push. ``None`` clears
        the cache — used after a delete so a future revival creates a
        fresh event rather than 404'ing.
        """
        with self.tx():
            self.conn.execute(
                "UPDATE hearings SET m365_event_id=? "
                "WHERE case_id=? AND hearing_key=?",
                (m365_event_id, case_id, hearing_key),
            )

    def all_active_hearings(self) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM hearings WHERE status != 'cancelled'"
        ).fetchall()
        return [self._row_to_hearing(r) for r in rows]

    @staticmethod
    def _row_to_hearing(row: sqlite3.Row) -> dict[str, Any]:
        d = dict(row)
        d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
        return d

    # --- deadlines ---

    def get_deadlines(self, case_id: str) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM deadlines WHERE case_id=?", (case_id,)
        ).fetchall()
        return [self._row_to_deadline(r) for r in rows]

    def get_deadline(self, case_id: str, deadline_key: str) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT * FROM deadlines WHERE case_id=? AND deadline_key=?",
            (case_id, deadline_key),
        ).fetchone()
        return self._row_to_deadline(row) if row else None

    def upsert_deadline(self, d: dict[str, Any]) -> None:
        self.conn.execute(
            """
            INSERT INTO deadlines
            (case_id, deadline_key, title, due_at_utc, timezone, notes,
             status, significance, deadline_type, gcal_event_id,
             docket_id, source_entry_ids, last_updated)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(case_id, deadline_key) DO UPDATE SET
              title=excluded.title,
              due_at_utc=excluded.due_at_utc,
              timezone=excluded.timezone,
              notes=excluded.notes,
              status=excluded.status,
              significance=COALESCE(excluded.significance, deadlines.significance),
              deadline_type=COALESCE(excluded.deadline_type, deadlines.deadline_type),
              gcal_event_id=COALESCE(excluded.gcal_event_id, deadlines.gcal_event_id),
              docket_id=COALESCE(excluded.docket_id, deadlines.docket_id),
              source_entry_ids=excluded.source_entry_ids,
              last_updated=excluded.last_updated
            """,
            (
                d["case_id"],
                d["deadline_key"],
                d["title"],
                d.get("due_at_utc"),
                d["timezone"],
                d.get("notes"),
                d["status"],
                d.get("significance"),
                d.get("deadline_type"),
                d.get("gcal_event_id"),
                d.get("docket_id"),
                json.dumps(d.get("source_entry_ids", [])),
                _now(),
            ),
        )

    def set_m365_id_for_deadline(
        self, case_id: str, deadline_key: str, m365_event_id: Optional[str],
    ) -> None:
        """Cache (or clear) the Graph-assigned event id for a deadline.
        Mirror of :meth:`set_m365_id_for_hearing`."""
        with self.tx():
            self.conn.execute(
                "UPDATE deadlines SET m365_event_id=? "
                "WHERE case_id=? AND deadline_key=?",
                (m365_event_id, case_id, deadline_key),
            )

    @staticmethod
    def _row_to_deadline(row: sqlite3.Row) -> dict[str, Any]:
        d = dict(row)
        d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
        return d

    # --- case summaries ---

    def upsert_case_summary(
        self,
        case_id: str,
        docket_id: int,
        *,
        summary: str,
        model: Optional[str],
        source_entry_ids: Optional[list[int]] = None,
    ) -> None:
        with self.tx():
            self.conn.execute(
                """
                INSERT INTO case_summaries
                  (case_id, docket_id, summary, model, source_entry_ids,
                   stale, stale_since, generated_at)
                VALUES (?, ?, ?, ?, ?, 0, NULL, ?)
                ON CONFLICT(case_id, docket_id) DO UPDATE SET
                  summary=excluded.summary,
                  model=excluded.model,
                  source_entry_ids=excluded.source_entry_ids,
                  stale=0,
                  stale_since=NULL,
                  generated_at=excluded.generated_at
                """,
                (
                    case_id,
                    docket_id,
                    summary,
                    model,
                    json.dumps(source_entry_ids or []),
                    _now(),
                ),
            )

    def mark_summary_stale(self, case_id: str, docket_id: int) -> None:
        """Flag the case_summaries row for ``(case_id, docket_id)`` as stale.

        Also bumps ``stale_since`` to NOW so the webhook debounce can tell
        "burst still arriving" from "burst settled." Each new stale-flagging
        entry resets the timestamp, which means the debounce window restarts
        from the LAST event in the burst, not the first.

        Only flips an existing row — for a docket with no summary yet, the
        absence of the row is itself the "needs regen" signal and the
        refresher will create it. We deliberately don't INSERT a stub here
        because the NOT NULL ``summary`` column has no honest empty value
        to seed, and the refresher always iterates configured dockets
        regardless of whether a row exists.
        """
        with self.tx():
            self.conn.execute(
                "UPDATE case_summaries SET stale=1, stale_since=? "
                "WHERE case_id=? AND docket_id=?",
                (_now(), case_id, docket_id),
            )

    def get_summary_stale_since(
        self, case_id: str, docket_id: int,
    ) -> Optional[str]:
        """Return the ISO timestamp of the most recent stale-flagging event,
        or None if the row isn't stale (or doesn't exist).

        Used by the webhook debounce to decide whether the burst has
        settled: if the timestamp is older than the debounce window, fire
        the regen; otherwise keep waiting.
        """
        row = self.conn.execute(
            "SELECT stale_since FROM case_summaries "
            "WHERE case_id=? AND docket_id=? AND stale=1",
            (case_id, docket_id),
        ).fetchone()
        if row is None:
            return None
        return row["stale_since"]

    def is_summary_stale(self, case_id: str, docket_id: int) -> bool:
        """Return True if the docket needs a (re)generated summary.

        Two equivalent signals: no row exists (new case / new docket
        hasn't been summarized yet) OR a row exists with ``stale=1``
        (a relevant operative-pleading or disposition entry landed
        after the last generation).
        """
        row = self.conn.execute(
            "SELECT stale FROM case_summaries WHERE case_id=? AND docket_id=?",
            (case_id, docket_id),
        ).fetchone()
        if row is None:
            return True
        return bool(row["stale"])

    def get_case_summaries(self, case_id: str) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT docket_id, summary, model, source_entry_ids, generated_at "
            "FROM case_summaries WHERE case_id=?",
            (case_id,),
        ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            try:
                d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
            except (TypeError, ValueError):
                d["source_entry_ids"] = []
            out.append(d)
        return out

    def get_docket_summary(
        self, case_id: str, docket_id: int
    ) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT docket_id, summary, model, source_entry_ids, generated_at "
            "FROM case_summaries WHERE case_id=? AND docket_id=?",
            (case_id, docket_id),
        ).fetchone()
        if not row:
            return None
        d = dict(row)
        try:
            d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
        except (TypeError, ValueError):
            d["source_entry_ids"] = []
        return d

    # --- webhook idempotency ---

    def webhook_seen(self, idempotency_key: str) -> bool:
        row = self.conn.execute(
            "SELECT 1 FROM webhook_events WHERE idempotency_key=?",
            (idempotency_key,),
        ).fetchone()
        return row is not None

    def mark_webhook_seen(self, idempotency_key: str, event_type: Optional[int]) -> None:
        self.conn.execute(
            "INSERT OR IGNORE INTO webhook_events (idempotency_key, event_type, received_at) "
            "VALUES (?, ?, ?)",
            (idempotency_key, event_type, _now()),
        )
