"""SQLite-backed state store.

Keeps:

* ``dockets`` — per-docket last-modified cutoff for the docket-level short-circuit
  plus cached metadata (court_id, case_name, docket_number, absolute_url) for
  description rendering at emit time.
* ``courts`` — citation_string + name lookup per court_id, fetched once.
* ``entries`` — every docket entry we've already processed, with a content
  fingerprint. Used for dedup and the docket-level last-modified cutoff.
* ``hearings`` — the canonical "logical" hearings per case. Each hearing has a
  stable ``hearing_key`` (chosen by the LLM) so reschedules and dial-in info
  updates land on the same row.
* ``deadlines`` — per-case filing deadlines (response/reply/brief due dates).
  Same shape as hearings: stable ``deadline_key`` per logical deadline, so
  granted extensions land on the same row rather than creating duplicates.
* ``case_summaries`` — opt-in per-docket prose summary ("what is this case
  about, who's involved, where does it stand") rendered into the index page.
  Generated by a separate higher-tier LLM pass over each docket's primary
  document + judgment if any; kept independent of the per-entry extractor
  so the cheaper extraction pipeline isn't affected.
* ``webhook_events`` — Idempotency-Key dedup for the webhook receiver.
"""

from __future__ import annotations

import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Iterator, Optional


def compact_recap_documents(entry: dict[str, Any]) -> list[dict[str, Any]]:
    """Build the subset of each recap_document we store locally.

    CourtListener returns roughly thirty fields per recap_document. We
    only keep the nine the calendar renderer and the summary pipeline
    actually read: identity (id, document_number, attachment_number,
    description), status flags (is_available, is_sealed), URLs
    (filepath_ia, filepath_local), and the extracted text body
    (plain_text). Everything else is CourtListener bookkeeping we'd
    never look at again. The result rides into the ``entries.recap_documents``
    JSON column.

    Ordered main-doc-first, then attachments by number, so calendar
    descriptions list documents in PACER's natural order.

    Lives in `store.py` (rather than `sync.py` where it was originally
    written) so the summary path can call it too — see
    `Store.refresh_entry_recap_documents` and the matching
    "Automatically rebuild stale cached recap_documents" design
    decision in AGENTS.md.
    """
    out: list[dict[str, Any]] = []
    for rd in entry.get("recap_documents") or []:
        out.append({
            "id": rd.get("id"),
            "document_number": rd.get("document_number"),
            "attachment_number": rd.get("attachment_number"),
            "description": (rd.get("description") or "").strip() or None,
            "is_available": bool(rd.get("is_available")),
            "is_sealed": bool(rd.get("is_sealed")),
            "filepath_ia": rd.get("filepath_ia") or None,
            "filepath_local": rd.get("filepath_local") or None,
            "plain_text": (rd.get("plain_text") or "").strip() or None,
        })

    def _key(d: dict[str, Any]) -> tuple[int, int]:
        # Sort attachment_number=None / 0 (the main doc) before numbered
        # attachments. document_number normally matches across rows on the
        # same entry, but treat it as the primary sort just in case.
        try:
            dn = int(d.get("document_number") or 0)
        except (TypeError, ValueError):
            dn = 0
        try:
            an = int(d.get("attachment_number") or 0)
        except (TypeError, ValueError):
            an = 0
        return (dn, an)

    out.sort(key=_key)
    return out


SCHEMA = """
CREATE TABLE IF NOT EXISTS dockets (
    docket_id INTEGER PRIMARY KEY,
    date_modified TEXT,
    date_last_filing TEXT,        -- CourtListener's "most recent document filing date" on the docket; the value the index page reads to surface "Last filing"
    last_synced_at TEXT NOT NULL,
    court_id TEXT,
    docket_number TEXT,
    case_name TEXT,
    absolute_url TEXT
);

CREATE TABLE IF NOT EXISTS courts (
    court_id TEXT PRIMARY KEY,
    citation_string TEXT,
    short_name TEXT,
    full_name TEXT,
    fetched_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS entries (
    docket_id INTEGER NOT NULL,
    entry_id INTEGER NOT NULL,
    entry_number INTEGER,        -- docket-position number (PACER's "[65]")
    date_filed TEXT,
    date_modified TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    description TEXT,            -- raw entry text; used to resolve cross-refs
    short_description TEXT,
    recap_documents TEXT,        -- JSON list of attached docs; surfaced as URLs in event description
    processed_at TEXT NOT NULL,
    PRIMARY KEY (docket_id, entry_id)
);

CREATE TABLE IF NOT EXISTS hearings (
    case_id TEXT NOT NULL,
    hearing_key TEXT NOT NULL,
    title TEXT NOT NULL,
    starts_at_utc TEXT,
    duration_minutes INTEGER,
    timezone TEXT NOT NULL,
    location TEXT,
    judge TEXT,
    notes TEXT,                  -- LLM-extracted summary of docket text; shown to subscribers
    audit_notes TEXT,            -- pipeline-synthesized audit trail (verify-pass / dedupe); never shown to LLM as input
    dial_in TEXT,
    status TEXT NOT NULL,        -- scheduled | held | cancelled | unknown
    significance TEXT,           -- "major" (default) | "minor" — calendar filter
    gcal_event_id TEXT,
    m365_event_id TEXT,
    docket_id INTEGER,           -- docket whose entry most recently updated this hearing
    source_entry_ids TEXT NOT NULL, -- JSON list of entry IDs
    last_updated TEXT NOT NULL,
    PRIMARY KEY (case_id, hearing_key)
);

CREATE TABLE IF NOT EXISTS deadlines (
    case_id TEXT NOT NULL,
    deadline_key TEXT NOT NULL,
    title TEXT NOT NULL,
    due_at_utc TEXT,              -- UTC ISO; renderer converts to court-local
    timezone TEXT NOT NULL,       -- IANA tz of the court the deadline was set in
    notes TEXT,                   -- LLM-extracted summary of docket text; shown to subscribers
    audit_notes TEXT,             -- pipeline-synthesized audit trail; never shown to LLM as input
    status TEXT NOT NULL,         -- pending | passed | met | cancelled | unknown
    significance TEXT,            -- "major" (default) | "minor" — calendar filter
    deadline_type TEXT,           -- response | reply | brief | other (informational)
    gcal_event_id TEXT,
    m365_event_id TEXT,
    docket_id INTEGER,            -- docket whose entry most recently updated this row
    source_entry_ids TEXT NOT NULL, -- JSON list of entry IDs
    last_updated TEXT NOT NULL,
    PRIMARY KEY (case_id, deadline_key)
);

CREATE TABLE IF NOT EXISTS case_summaries (
    case_id TEXT NOT NULL,
    docket_id INTEGER NOT NULL,
    summary TEXT NOT NULL,
    model TEXT,
    source_entry_ids TEXT,         -- JSON list of CourtListener entry IDs fed to the LLM
    stale INTEGER NOT NULL DEFAULT 0,  -- 1 when sync saw a new primary document or disposition that may invalidate the prose
    stale_since TEXT,              -- ISO timestamp of the most recent stale-flagging entry; used by the webhook debounce so a burst of PACER uploads coalesces into one regeneration
    generated_at TEXT NOT NULL,
    PRIMARY KEY (case_id, docket_id)
);

CREATE TABLE IF NOT EXISTS webhook_events (
    -- CourtListener sends an Idempotency-Key (UUID) header on every webhook
    -- delivery. We store seen keys so retries are no-ops.
    idempotency_key TEXT PRIMARY KEY,
    event_type INTEGER,
    received_at TEXT NOT NULL
);
"""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


_AUDIT_PARAGRAPH_PREFIXES = ("[verify-pass]", "[dedupe]")


def _split_audit_segments(notes: Optional[str]) -> tuple[str, str]:
    """Separate pipeline-synthesized audit paragraphs from docket-derived notes.

    A paragraph (text separated by blank lines) is "audit" if its first
    non-whitespace characters are ``[verify-pass]`` or ``[dedupe]``. These
    prefixes are written ONLY by :class:`CaseSyncer` audit passes, never
    by the per-entry extractor or by docket text, so the split is unambiguous.

    Returns ``(clean_notes, audit_text)``: ``clean_notes`` is the original
    string with audit paragraphs removed; ``audit_text`` joins the audit
    paragraphs with blank-line separators. Either can be empty. The
    migration helper persists them to the ``notes`` / ``audit_notes``
    columns respectively. Inline bracketed text inside a docket-derived
    paragraph is left alone — only paragraphs that LEAD with the prefix
    are moved.
    """
    if not notes:
        return "", ""
    paragraphs = notes.split("\n\n")
    kept: list[str] = []
    moved: list[str] = []
    for p in paragraphs:
        stripped = p.lstrip()
        if any(stripped.startswith(prefix) for prefix in _AUDIT_PARAGRAPH_PREFIXES):
            moved.append(p.strip())
        else:
            kept.append(p)
    clean_notes = "\n\n".join(kept).strip()
    audit_text = "\n\n".join(moved).strip()
    return clean_notes, audit_text


class Store:
    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        # check_same_thread=False so the webhook server (ThreadingHTTPServer)
        # can use this connection from worker threads. We serialize callers
        # explicitly — see WebhookServer.process_locked.
        self.conn = sqlite3.connect(self.path, check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        # WAL + a small busy_timeout let the polling `sync` process and the
        # long-running `serve` process safely share the same DB file. Without
        # these the second writer raises SQLITE_BUSY *immediately* on any
        # commit overlap: a webhook delivery that lands mid-sync would
        # bubble up as HTTP 500 (CourtListener retries via Idempotency-Key, no data
        # loss but transient errors in the webhook log), and a sync that
        # collides with a webhook would abort the whole invocation. WAL
        # lets readers and one writer coexist; busy_timeout makes the
        # loser block-and-retry for up to 5 seconds before raising — long
        # enough to cover any of our actual transactions (single-row
        # UPSERTs, no long-held writes). Sidecar `<db>-wal` and `<db>-shm`
        # files appear next to the DB; include them in backups.
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.execute("PRAGMA busy_timeout=5000")
        self.conn.executescript(SCHEMA)
        self._migrate()
        self.conn.commit()

    def _migrate(self) -> None:
        """Idempotent ALTER TABLE for columns added after first release."""
        for table, col, type_ in [
            ("dockets", "court_id", "TEXT"),
            ("dockets", "docket_number", "TEXT"),
            ("dockets", "case_name", "TEXT"),
            ("dockets", "absolute_url", "TEXT"),
            ("dockets", "date_last_filing", "TEXT"),
            ("hearings", "docket_id", "INTEGER"),
            ("hearings", "significance", "TEXT"),
            ("entries", "date_filed", "TEXT"),
            ("entries", "entry_number", "INTEGER"),
            ("entries", "description", "TEXT"),
            ("entries", "short_description", "TEXT"),
            ("entries", "recap_documents", "TEXT"),
            ("hearings", "m365_event_id", "TEXT"),
            ("deadlines", "m365_event_id", "TEXT"),
            ("hearings", "audit_notes", "TEXT"),
            ("deadlines", "audit_notes", "TEXT"),
            ("case_summaries", "stale", "INTEGER NOT NULL DEFAULT 0"),
            ("case_summaries", "stale_since", "TEXT"),
        ]:
            try:
                self.conn.execute(f"ALTER TABLE {table} ADD COLUMN {col} {type_}")
            except sqlite3.OperationalError:
                pass  # column already exists
        # Drop columns that older releases populated for description rendering.
        # Renderer no longer reads them; storing them was wasted IO and disk.
        for col in ("description_text", "pdf_text_excerpt"):
            try:
                self.conn.execute(f"ALTER TABLE entries DROP COLUMN {col}")
            except sqlite3.OperationalError:
                pass  # column doesn't exist (fresh DB)
        # Index lives in _migrate (not SCHEMA) because it depends on a column
        # added by ALTER TABLE above; running it from SCHEMA on an old DB
        # would reference entry_number before the migration creates it.
        self.conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_entries_docket_entry_number "
            "ON entries (docket_id, entry_number)"
        )
        # Move existing [verify-pass] / [dedupe] paragraphs from notes to
        # audit_notes. The verify pass was previously writing audit trail
        # into the same `notes` column it later read as docket evidence,
        # producing circular self-confirmation (the McGonigal trial regression).
        # The split makes that impossible structurally: verify pass writes to
        # audit_notes, reads only notes. This migration recategorizes the
        # already-written legacy rows. Idempotent — second run finds nothing
        # to move because the prefixes only live in notes pre-migration.
        # Un-prefixed legacy brackets (e.g. "[Trial vacated by guilty plea ...]"
        # without a [verify-pass] header) are intentionally left in notes;
        # they may be real docket text that happens to be bracketed, so a
        # blanket move is unsafe. Those rows get hand-cleanup.
        self._migrate_audit_segments()

    def _migrate_audit_segments(self) -> None:
        """Split existing [verify-pass] / [dedupe] paragraphs out of `notes`
        into `audit_notes`. Called by :meth:`_migrate`; safe to re-run."""
        for table, key_col in (("hearings", "hearing_key"), ("deadlines", "deadline_key")):
            rows = self.conn.execute(
                f"SELECT case_id, {key_col}, notes, audit_notes FROM {table} "
                f"WHERE notes IS NOT NULL "
                f"  AND (notes LIKE '%[verify-pass]%' OR notes LIKE '%[dedupe]%')"
            ).fetchall()
            for row in rows:
                clean_notes, extracted = _split_audit_segments(row["notes"])
                if not extracted:
                    continue
                # Merge any pre-existing audit_notes with the newly-extracted
                # paragraphs (extracted ones come last, preserving chronology).
                existing_audit = (row["audit_notes"] or "").strip()
                new_audit = "\n\n".join(
                    p for p in (existing_audit, extracted) if p
                )
                self.conn.execute(
                    f"UPDATE {table} SET notes=?, audit_notes=? "
                    f"WHERE case_id=? AND {key_col}=?",
                    (
                        clean_notes or None,
                        new_audit or None,
                        row["case_id"],
                        row[key_col],
                    ),
                )

    def close(self) -> None:
        self.conn.close()

    @contextmanager
    def tx(self) -> Iterator[sqlite3.Connection]:
        try:
            yield self.conn
            self.conn.commit()
        except Exception:
            self.conn.rollback()
            raise

    # --- dockets ---

    def docket_last_modified(self, docket_id: int) -> Optional[str]:
        row = self.conn.execute(
            "SELECT date_modified FROM dockets WHERE docket_id=?",
            (docket_id,),
        ).fetchone()
        return row["date_modified"] if row else None

    def set_docket_last_modified(self, docket_id: int, date_modified: str) -> None:
        # Preserves any metadata columns set by upsert_docket_meta.
        self.conn.execute(
            """
            INSERT INTO dockets (docket_id, date_modified, last_synced_at)
            VALUES (?, ?, ?)
            ON CONFLICT(docket_id) DO UPDATE SET
              date_modified=excluded.date_modified,
              last_synced_at=excluded.last_synced_at
            """,
            (docket_id, date_modified, _now()),
        )

    def bump_docket_last_modified(self, docket_id: int, candidate: str) -> None:
        """Advance ``dockets.date_modified`` only if ``candidate`` is newer.

        ``date_modified`` is the docket-level short-circuit cutoff
        (``sync_case`` skips a docket whose CourtListener ``date_modified`` hasn't
        moved past this value). The polling path sets it to the parent
        docket's authoritative value at end-of-loop; the webhook path
        never sees the parent docket per delivery, so without this bump
        the cutoff would stay frozen at the last poll time and
        webhook-only deployments would never short-circuit.

        Done as a conditional UPDATE so out-of-order webhook deliveries
        can't move the value backwards. The index page's "Last filing"
        column reads from a separate column (``date_last_filing``); this
        is the short-circuit cutoff, not the user-visible date.
        """
        self.conn.execute(
            """
            INSERT INTO dockets (docket_id, date_modified, last_synced_at)
            VALUES (?, ?, ?)
            ON CONFLICT(docket_id) DO UPDATE SET
              date_modified=excluded.date_modified,
              last_synced_at=excluded.last_synced_at
              WHERE dockets.date_modified IS NULL
                 OR dockets.date_modified < excluded.date_modified
            """,
            (docket_id, candidate, _now()),
        )

    def upsert_docket_meta(self, docket_id: int, meta: dict[str, Any]) -> None:
        """Cache the human-readable docket metadata we display in event bodies.

        ``date_last_filing`` (CourtListener's "most recent document filing date") is
        persisted here when present so the index page can render an
        unambiguous "Last filing" date that doesn't bump on OCR / metadata
        churn the way ``date_modified`` does. None on the input leaves any
        previously-cached value alone.
        """
        self.conn.execute(
            """
            INSERT INTO dockets
              (docket_id, last_synced_at, court_id, docket_number, case_name,
               absolute_url, date_last_filing)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(docket_id) DO UPDATE SET
              court_id=excluded.court_id,
              docket_number=excluded.docket_number,
              case_name=excluded.case_name,
              absolute_url=excluded.absolute_url,
              date_last_filing=COALESCE(
                  excluded.date_last_filing, dockets.date_last_filing
              )
            """,
            (
                docket_id,
                _now(),
                meta.get("court_id"),
                meta.get("docket_number"),
                meta.get("case_name"),
                meta.get("absolute_url"),
                meta.get("date_last_filing"),
            ),
        )

    def bump_docket_last_filing(self, docket_id: int, candidate: str) -> None:
        """Advance ``dockets.date_last_filing`` only if ``candidate`` is newer.

        CourtListener stamps the docket-level ``date_last_filing`` server-side, but
        webhook deliveries don't refetch the parent docket on every event,
        so without this the value would lag the entries we just processed.
        Each ``process_entry`` call passes the entry's own ``date_filed``
        through here; conditional update is forward-only so out-of-order
        webhook deliveries can't move the cutoff backwards.
        """
        if not candidate:
            return
        self.conn.execute(
            """
            INSERT INTO dockets (docket_id, date_last_filing, last_synced_at)
            VALUES (?, ?, ?)
            ON CONFLICT(docket_id) DO UPDATE SET
              date_last_filing=excluded.date_last_filing,
              last_synced_at=excluded.last_synced_at
              WHERE dockets.date_last_filing IS NULL
                 OR dockets.date_last_filing < excluded.date_last_filing
            """,
            (docket_id, candidate, _now()),
        )

    def get_docket_meta(self, docket_id: int) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT court_id, docket_number, case_name, absolute_url, "
            "date_last_filing "
            "FROM dockets WHERE docket_id=?",
            (docket_id,),
        ).fetchone()
        return dict(row) if row else None

    def known_docket_ids(self) -> set[int]:
        """Return every docket_id that has a row in the ``dockets`` table.

        Used by ``case-calendar sync --only-new`` to skip cases whose
        dockets the syncer has already seen at least once.
        """
        return {
            row["docket_id"]
            for row in self.conn.execute("SELECT docket_id FROM dockets")
        }

    # --- courts ---

    def get_court_citation(self, court_id: str) -> Optional[str]:
        row = self.conn.execute(
            "SELECT citation_string FROM courts WHERE court_id=?",
            (court_id,),
        ).fetchone()
        return row["citation_string"] if row else None

    def upsert_court(
        self,
        court_id: str,
        citation_string: Optional[str],
        short_name: Optional[str],
        full_name: Optional[str],
    ) -> None:
        self.conn.execute(
            "INSERT OR REPLACE INTO courts "
            "(court_id, citation_string, short_name, full_name, fetched_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (court_id, citation_string, short_name, full_name, _now()),
        )

    # --- entries ---

    def entry_seen(self, docket_id: int, entry_id: int, fingerprint: str) -> bool:
        row = self.conn.execute(
            "SELECT fingerprint FROM entries WHERE docket_id=? AND entry_id=?",
            (docket_id, entry_id),
        ).fetchone()
        return row is not None and row["fingerprint"] == fingerprint

    def mark_entry(
        self,
        docket_id: int,
        entry_id: int,
        date_modified: str,
        fingerprint: str,
        *,
        date_filed: Optional[str] = None,
        entry_number: Optional[int] = None,
        description: Optional[str] = None,
        short_description: Optional[str] = None,
        recap_documents: Optional[list[dict[str, Any]]] = None,
    ) -> None:
        # Always overwrite recap_documents — adding/removing docs is exactly
        # the change we want to surface in the calendar. Pass None to leave
        # the existing JSON untouched (filter-failed entries don't supply it).
        docs_json = json.dumps(recap_documents) if recap_documents is not None else None
        self.conn.execute(
            """
            INSERT INTO entries
              (docket_id, entry_id, entry_number, date_filed, date_modified,
               fingerprint, description, short_description, recap_documents,
               processed_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(docket_id, entry_id) DO UPDATE SET
              entry_number=COALESCE(excluded.entry_number, entries.entry_number),
              date_filed=COALESCE(excluded.date_filed, entries.date_filed),
              date_modified=excluded.date_modified,
              fingerprint=excluded.fingerprint,
              description=COALESCE(excluded.description, entries.description),
              short_description=COALESCE(
                  excluded.short_description, entries.short_description
              ),
              recap_documents=COALESCE(
                  excluded.recap_documents, entries.recap_documents
              ),
              processed_at=excluded.processed_at
            """,
            (
                docket_id,
                entry_id,
                entry_number,
                date_filed,
                date_modified,
                fingerprint,
                description,
                short_description,
                docs_json,
                _now(),
            ),
        )

    def refresh_entry_recap_documents(
        self, entry: dict[str, Any], *, docket_id: int,
    ) -> bool:
        """Overwrite an existing entry's stored ``recap_documents`` with a
        fresh version built from a current CourtListener response. Leaves every
        other column — fingerprint, description, status timestamps —
        untouched.

        Used by `summary.find_primary_documents` to repair stale cache rows when the
        cached recap_documents look out of date — see the matching
        "Automatically rebuild stale cached recap_documents" Key Design Decision in
        AGENTS.md. We deliberately do NOT touch the fingerprint here:
        if we re-stored a fresh fingerprint, the next sync would see
        stored == computed and skip the normal extract path, which is
        the path we want to fire when an actual content change lands.
        This is a side-channel update to the cached data only.

        ``docket_id`` is taken as an explicit kwarg rather than read
        from the entry dict because CourtListener serializes the docket as a URL
        string in the entry payload, not the integer the local store
        keys on.

        Returns True when a row existed and was updated; False otherwise
        (no-op when the entry isn't already in the local store).
        """
        entry_id = entry.get("id")
        if not entry_id:
            return False
        new_recap_documents = compact_recap_documents(entry)
        cur = self.conn.execute(
            "UPDATE entries SET recap_documents=? "
            "WHERE docket_id=? AND entry_id=?",
            (json.dumps(new_recap_documents), docket_id, entry_id),
        )
        return cur.rowcount > 0

    def get_entry_by_number(
        self, docket_id: int, entry_number: int
    ) -> Optional[dict[str, Any]]:
        """Look up a docket entry by its position number (PACER's "[65]").

        Returns the stored description / short_description so callers can
        resolve cross-references like "ORDER granting 65 Motion ..." without
        a CourtListener round-trip. Older entries (pre-migration) won't have description
        stored — we return whatever is there.
        """
        row = self.conn.execute(
            "SELECT entry_id, entry_number, date_filed, description, short_description "
            "FROM entries WHERE docket_id=? AND entry_number=?",
            (docket_id, entry_number),
        ).fetchone()
        return dict(row) if row else None

    def get_entries_with_body(self, docket_id: int) -> list[dict[str, Any]]:
        """All stored entries on the docket whose description body was kept.

        Used by the summary pipeline to find primary documents and
        dispositions locally instead of re-fetching docket-entries pages
        from CourtListener right after sync wrote them down. Filter-failed stubs
        (description IS NULL) are excluded. ``recap_documents`` is
        deserialized from the JSON column on the way out.
        """
        rows = self.conn.execute(
            """
            SELECT entry_id, entry_number, date_filed,
                   description, short_description, recap_documents
            FROM entries
            WHERE docket_id=? AND description IS NOT NULL
            ORDER BY date_filed
            """,
            (docket_id,),
        ).fetchall()
        out: list[dict[str, Any]] = []
        for r in rows:
            d = dict(r)
            d["recap_documents"] = json.loads(d.get("recap_documents") or "[]")
            # Shape matches what CourtListener returns to find_primary_documents
            # ("id" key for entry_id), so callers can treat both paths
            # interchangeably.
            d["id"] = d.pop("entry_id")
            out.append(d)
        return out

    def get_recent_relevant_entries(
        self, docket_id: int, before_date_modified: str, limit: int = 5
    ) -> list[dict[str, Any]]:
        """Return the last `limit` hearing-relevant entries that came before
        the given timestamp on the docket, newest first.

        "Hearing-relevant" is detected by ``description IS NOT NULL`` — we
        only persist description for entries that passed the regex pre-filter
        in the sync pipeline (filter-failed entries are stored as fingerprint
        stubs with NULL description). This gives the LLM context on what
        recently happened on the docket so it can name a hearing correctly
        even when the entry that sets it (e.g. "PAPERLESS Order Setting
        Telephonic Pretrial Conference") doesn't itself name the underlying
        motion's subject — the answer often lives in a recent motion that
        the order doesn't cite by docket position.
        """
        rows = self.conn.execute(
            """
            SELECT entry_id, entry_number, date_filed, description, short_description
            FROM entries
            WHERE docket_id=? AND date_modified < ? AND description IS NOT NULL
            ORDER BY date_modified DESC LIMIT ?
            """,
            (docket_id, before_date_modified, limit),
        ).fetchall()
        return [dict(r) for r in rows]

    def get_entry_numbers(
        self, entry_ids: Iterable[int]
    ) -> dict[int, int]:
        """Return ``entry_id -> entry_number`` for known entries.

        Used by emit-time description rendering to surface PACER docket
        positions (the "[65]" subscribers see in the CourtListener UI) alongside the
        opaque CourtListener entry IDs. Entries with NULL entry_number
        (rare — pre-migration rows) and unknown ids are omitted.
        """
        ids = [int(i) for i in entry_ids]
        if not ids:
            return {}
        placeholders = ",".join("?" * len(ids))
        rows = self.conn.execute(
            f"SELECT entry_id, entry_number FROM entries "
            f"WHERE entry_id IN ({placeholders}) "
            f"AND entry_number IS NOT NULL",
            ids,
        ).fetchall()
        return {r["entry_id"]: r["entry_number"] for r in rows}

    def get_entry_documents(
        self, entry_ids: Iterable[int]
    ) -> dict[int, list[dict[str, Any]]]:
        """Return ``entry_id -> [recap_document, ...]`` for known entries.

        Each list element is the compact JSON we persist on the entry row
        (id, document_number, attachment_number, description, status flags,
        filepath_ia, filepath_local). Used by emit-time description rendering
        to surface clickable document URLs next to each source entry. Entries
        with NULL recap_documents (pre-migration rows, or filter-failed
        stubs) and unknown ids are omitted.
        """
        ids = [int(i) for i in entry_ids]
        if not ids:
            return {}
        placeholders = ",".join("?" * len(ids))
        rows = self.conn.execute(
            f"SELECT entry_id, recap_documents FROM entries "
            f"WHERE entry_id IN ({placeholders}) "
            f"AND recap_documents IS NOT NULL",
            ids,
        ).fetchall()
        out: dict[int, list[dict[str, Any]]] = {}
        for r in rows:
            try:
                out[r["entry_id"]] = json.loads(r["recap_documents"]) or []
            except (TypeError, ValueError):
                continue
        return out

    def latest_entry_modified(self, docket_id: int) -> Optional[str]:
        row = self.conn.execute(
            "SELECT MAX(date_modified) AS m FROM entries WHERE docket_id=?",
            (docket_id,),
        ).fetchone()
        return row["m"] if row and row["m"] else None

    def get_case_aggregates(
        self, docket_ids: Iterable[int]
    ) -> dict[str, Optional[str]]:
        """Return ``{"date_filed": ..., "last_filing_date": ...}`` across a case's dockets.

        ``date_filed`` = MIN(entries.date_filed) — the first filed entry on
        any of the case's dockets is the closest stand-in for the case's
        filing date (we don't store the docket-level date_filed CourtListener exposes,
        so this is the cheap derived value).

        ``last_filing_date`` = MAX(dockets.date_last_filing) — CourtListener's
        authoritative "most recent document filing date" rolled up across
        a multi-docket case. Distinct from ``dockets.date_modified``, which
        bumps on OCR / metadata churn and would mislabel non-filing updates
        as new activity.

        Either value may be None when no rows are present yet.
        """
        ids = [int(i) for i in docket_ids]
        if not ids:
            return {"date_filed": None, "last_filing_date": None}
        placeholders = ",".join("?" * len(ids))
        df = self.conn.execute(
            f"SELECT MIN(date_filed) AS d FROM entries "
            f"WHERE docket_id IN ({placeholders}) AND date_filed IS NOT NULL",
            ids,
        ).fetchone()
        lf = self.conn.execute(
            f"SELECT MAX(date_last_filing) AS d FROM dockets "
            f"WHERE docket_id IN ({placeholders}) "
            f"AND date_last_filing IS NOT NULL",
            ids,
        ).fetchone()
        return {
            "date_filed": df["d"] if df and df["d"] else None,
            "last_filing_date": lf["d"] if lf and lf["d"] else None,
        }

    # --- hearings ---

    def get_hearings(self, case_id: str) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM hearings WHERE case_id=?", (case_id,)
        ).fetchall()
        return [self._row_to_hearing(r) for r in rows]

    def get_hearings_in_court(
        self, case_id: str, court_id: str,
    ) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            """
            SELECT h.* FROM hearings h
            LEFT JOIN dockets d ON d.docket_id = h.docket_id
            WHERE h.case_id = ?
              AND (h.docket_id IS NULL OR d.court_id IS NULL OR d.court_id = ?)
            """,
            (case_id, court_id),
        ).fetchall()
        return [self._row_to_hearing(r) for r in rows]

    def find_concurrent_hearing_clusters(
        self, case_id: str,
    ) -> list[list[dict[str, Any]]]:
        """Future scheduled hearings sharing (docket_id, starts_at_utc).

        Returns a list of clusters, each a list of >=2 hearing dicts with
        ``source_entry_ids`` already JSON-decoded. A single court cannot
        hold two hearings on one docket at the same date and time, so
        equal ``(docket_id, starts_at_utc)`` across ``status='scheduled'``
        rows is a signal that the per-entry extractor split one logical
        event across keys (e.g. a stipulation referred to "Hearing on
        Motion for Summary Judgment" and the signed order called it
        "Motion Hearing" — same slot, two ``hearing_key``s). The end-of-
        sync dedupe sweep in :class:`CaseSyncer` resolves these via a
        focused LLM call. Past hearings are excluded — the auto-held
        sweep handles them.
        """
        now_iso = datetime.now(timezone.utc).isoformat()
        rows = self.conn.execute(
            """
            SELECT * FROM hearings
            WHERE case_id=? AND status='scheduled'
              AND starts_at_utc IS NOT NULL AND starts_at_utc >= ?
              AND docket_id IS NOT NULL
            ORDER BY docket_id, starts_at_utc, hearing_key
            """,
            (case_id, now_iso),
        ).fetchall()
        clusters: dict[tuple[int, str], list[dict[str, Any]]] = {}
        for r in rows:
            h = self._row_to_hearing(r)
            key = (h["docket_id"], h["starts_at_utc"])
            clusters.setdefault(key, []).append(h)
        return [c for c in clusters.values() if len(c) > 1]

    def get_hearing(self, case_id: str, hearing_key: str) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT * FROM hearings WHERE case_id=? AND hearing_key=?",
            (case_id, hearing_key),
        ).fetchone()
        return self._row_to_hearing(row) if row else None

    def upsert_hearing(self, h: dict[str, Any]) -> None:
        self.conn.execute(
            """
            INSERT INTO hearings
            (case_id, hearing_key, title, starts_at_utc, duration_minutes, timezone,
             location, judge, notes, audit_notes, dial_in, status, significance,
             gcal_event_id, docket_id, source_entry_ids, last_updated)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(case_id, hearing_key) DO UPDATE SET
              title=excluded.title,
              starts_at_utc=excluded.starts_at_utc,
              duration_minutes=excluded.duration_minutes,
              timezone=excluded.timezone,
              location=excluded.location,
              judge=excluded.judge,
              notes=excluded.notes,
              audit_notes=COALESCE(excluded.audit_notes, hearings.audit_notes),
              dial_in=excluded.dial_in,
              status=excluded.status,
              significance=COALESCE(excluded.significance, hearings.significance),
              gcal_event_id=COALESCE(excluded.gcal_event_id, hearings.gcal_event_id),
              docket_id=COALESCE(excluded.docket_id, hearings.docket_id),
              source_entry_ids=excluded.source_entry_ids,
              last_updated=excluded.last_updated
            """,
            (
                h["case_id"],
                h["hearing_key"],
                h["title"],
                h.get("starts_at_utc"),
                h.get("duration_minutes"),
                h["timezone"],
                h.get("location"),
                h.get("judge"),
                h.get("notes"),
                h.get("audit_notes"),
                h.get("dial_in"),
                h["status"],
                h.get("significance"),
                h.get("gcal_event_id"),
                h.get("docket_id"),
                json.dumps(h.get("source_entry_ids", [])),
                _now(),
            ),
        )

    def set_gcal_id(self, case_id: str, hearing_key: str, gcal_event_id: str) -> None:
        self.conn.execute(
            "UPDATE hearings SET gcal_event_id=? WHERE case_id=? AND hearing_key=?",
            (gcal_event_id, case_id, hearing_key),
        )

    def set_m365_id_for_hearing(
        self, case_id: str, hearing_key: str, m365_event_id: Optional[str],
    ) -> None:
        """Cache (or clear) the Graph-assigned event id for a hearing.

        Graph generates ids server-side, so we persist them after first
        create to avoid a $filter lookup on every push. ``None`` clears
        the cache — used after a delete so a future revival creates a
        fresh event rather than 404'ing.
        """
        with self.tx():
            self.conn.execute(
                "UPDATE hearings SET m365_event_id=? "
                "WHERE case_id=? AND hearing_key=?",
                (m365_event_id, case_id, hearing_key),
            )

    def all_active_hearings(self) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM hearings WHERE status != 'cancelled'"
        ).fetchall()
        return [self._row_to_hearing(r) for r in rows]

    @staticmethod
    def _row_to_hearing(row: sqlite3.Row) -> dict[str, Any]:
        d = dict(row)
        # source_entry_ids is JSON; a corrupted column (manual SQL edit,
        # aborted migration, partial write) shouldn't crash every caller
        # that reads the row. Fall back to an empty list and keep going —
        # the verify sweeps and any downstream LLM context just lose one
        # row's provenance, not the whole sync.
        try:
            d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
        except (json.JSONDecodeError, TypeError):
            d["source_entry_ids"] = []
        return d

    # --- deadlines ---

    def get_deadlines(self, case_id: str) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM deadlines WHERE case_id=?", (case_id,)
        ).fetchall()
        return [self._row_to_deadline(r) for r in rows]

    def get_deadlines_in_court(
        self, case_id: str, court_id: str,
    ) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            """
            SELECT dl.* FROM deadlines dl
            LEFT JOIN dockets d ON d.docket_id = dl.docket_id
            WHERE dl.case_id = ?
              AND (dl.docket_id IS NULL OR d.court_id IS NULL OR d.court_id = ?)
            """,
            (case_id, court_id),
        ).fetchall()
        return [self._row_to_deadline(r) for r in rows]

    def get_deadline(self, case_id: str, deadline_key: str) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT * FROM deadlines WHERE case_id=? AND deadline_key=?",
            (case_id, deadline_key),
        ).fetchone()
        return self._row_to_deadline(row) if row else None

    def upsert_deadline(self, d: dict[str, Any]) -> None:
        self.conn.execute(
            """
            INSERT INTO deadlines
            (case_id, deadline_key, title, due_at_utc, timezone, notes, audit_notes,
             status, significance, deadline_type, gcal_event_id,
             docket_id, source_entry_ids, last_updated)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(case_id, deadline_key) DO UPDATE SET
              title=excluded.title,
              due_at_utc=excluded.due_at_utc,
              timezone=excluded.timezone,
              notes=excluded.notes,
              audit_notes=COALESCE(excluded.audit_notes, deadlines.audit_notes),
              status=excluded.status,
              significance=COALESCE(excluded.significance, deadlines.significance),
              deadline_type=COALESCE(excluded.deadline_type, deadlines.deadline_type),
              gcal_event_id=COALESCE(excluded.gcal_event_id, deadlines.gcal_event_id),
              docket_id=COALESCE(excluded.docket_id, deadlines.docket_id),
              source_entry_ids=excluded.source_entry_ids,
              last_updated=excluded.last_updated
            """,
            (
                d["case_id"],
                d["deadline_key"],
                d["title"],
                d.get("due_at_utc"),
                d["timezone"],
                d.get("notes"),
                d.get("audit_notes"),
                d["status"],
                d.get("significance"),
                d.get("deadline_type"),
                d.get("gcal_event_id"),
                d.get("docket_id"),
                json.dumps(d.get("source_entry_ids", [])),
                _now(),
            ),
        )

    def set_m365_id_for_deadline(
        self, case_id: str, deadline_key: str, m365_event_id: Optional[str],
    ) -> None:
        """Cache (or clear) the Graph-assigned event id for a deadline.
        Mirror of :meth:`set_m365_id_for_hearing`."""
        with self.tx():
            self.conn.execute(
                "UPDATE deadlines SET m365_event_id=? "
                "WHERE case_id=? AND deadline_key=?",
                (m365_event_id, case_id, deadline_key),
            )

    @staticmethod
    def _row_to_deadline(row: sqlite3.Row) -> dict[str, Any]:
        d = dict(row)
        # Same corruption-tolerant fallback as `_row_to_hearing`.
        try:
            d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
        except (json.JSONDecodeError, TypeError):
            d["source_entry_ids"] = []
        return d

    # --- case summaries ---

    def upsert_case_summary(
        self,
        case_id: str,
        docket_id: int,
        *,
        summary: str,
        model: Optional[str],
        source_entry_ids: Optional[list[int]] = None,
    ) -> None:
        with self.tx():
            self.conn.execute(
                """
                INSERT INTO case_summaries
                  (case_id, docket_id, summary, model, source_entry_ids,
                   stale, stale_since, generated_at)
                VALUES (?, ?, ?, ?, ?, 0, NULL, ?)
                ON CONFLICT(case_id, docket_id) DO UPDATE SET
                  summary=excluded.summary,
                  model=excluded.model,
                  source_entry_ids=excluded.source_entry_ids,
                  stale=0,
                  stale_since=NULL,
                  generated_at=excluded.generated_at
                """,
                (
                    case_id,
                    docket_id,
                    summary,
                    model,
                    json.dumps(source_entry_ids or []),
                    _now(),
                ),
            )

    def mark_summary_stale(self, case_id: str, docket_id: int) -> None:
        """Flag the case_summaries row for ``(case_id, docket_id)`` as stale.

        Also bumps ``stale_since`` to NOW so the webhook debounce can tell
        "burst still arriving" from "burst settled." Each new stale-flagging
        entry resets the timestamp, which means the debounce window restarts
        from the LAST event in the burst, not the first.

        Only flips an existing row — for a docket with no summary yet, the
        absence of the row is itself the "needs regen" signal and the
        refresher will create it. We deliberately don't INSERT a stub here
        because the NOT NULL ``summary`` column has no honest empty value
        to seed, and the refresher always iterates configured dockets
        regardless of whether a row exists.
        """
        with self.tx():
            self.conn.execute(
                "UPDATE case_summaries SET stale=1, stale_since=? "
                "WHERE case_id=? AND docket_id=?",
                (_now(), case_id, docket_id),
            )

    def get_summary_stale_since(
        self, case_id: str, docket_id: int,
    ) -> Optional[str]:
        """Return the ISO timestamp of the most recent stale-flagging event,
        or None if the row isn't stale (or doesn't exist).

        Used by the webhook debounce to decide whether the burst has
        settled: if the timestamp is older than the debounce window, fire
        the regen; otherwise keep waiting.
        """
        row = self.conn.execute(
            "SELECT stale_since FROM case_summaries "
            "WHERE case_id=? AND docket_id=? AND stale=1",
            (case_id, docket_id),
        ).fetchone()
        if row is None:
            return None
        return row["stale_since"]

    def is_summary_stale(self, case_id: str, docket_id: int) -> bool:
        """Return True if the docket needs a (re)generated summary.

        Two equivalent signals: no row exists (new case / new docket
        hasn't been summarized yet) OR a row exists with ``stale=1``
        (a relevant primary-document or disposition entry landed
        after the last generation).
        """
        row = self.conn.execute(
            "SELECT stale FROM case_summaries WHERE case_id=? AND docket_id=?",
            (case_id, docket_id),
        ).fetchone()
        if row is None:
            return True
        return bool(row["stale"])

    def get_case_summaries(self, case_id: str) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT docket_id, summary, model, source_entry_ids, generated_at "
            "FROM case_summaries WHERE case_id=?",
            (case_id,),
        ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            try:
                d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
            except (TypeError, ValueError):
                d["source_entry_ids"] = []
            out.append(d)
        return out

    def get_docket_summary(
        self, case_id: str, docket_id: int
    ) -> Optional[dict[str, Any]]:
        row = self.conn.execute(
            "SELECT docket_id, summary, model, source_entry_ids, generated_at "
            "FROM case_summaries WHERE case_id=? AND docket_id=?",
            (case_id, docket_id),
        ).fetchone()
        if not row:
            return None
        d = dict(row)
        try:
            d["source_entry_ids"] = json.loads(d.get("source_entry_ids") or "[]")
        except (TypeError, ValueError):
            d["source_entry_ids"] = []
        return d

    # --- webhook idempotency ---

    def webhook_seen(self, idempotency_key: str) -> bool:
        row = self.conn.execute(
            "SELECT 1 FROM webhook_events WHERE idempotency_key=?",
            (idempotency_key,),
        ).fetchone()
        return row is not None

    def mark_webhook_seen(self, idempotency_key: str, event_type: Optional[int]) -> None:
        self.conn.execute(
            "INSERT OR IGNORE INTO webhook_events (idempotency_key, event_type, received_at) "
            "VALUES (?, ?, ?)",
            (idempotency_key, event_type, _now()),
        )

    # --- prune helpers ---

    # Tables that carry a docket_id FK. Order matters for delete_docket: the
    # `dockets` row must be removed last so a mid-DELETE crash leaves the
    # parent row pointing at no children rather than child rows pointing at
    # a parent that has already been deleted.
    _DOCKET_CHILD_TABLES = ("entries", "hearings", "deadlines", "case_summaries")
    _DOCKET_TABLES = _DOCKET_CHILD_TABLES + ("dockets",)

    def list_all_docket_ids(self) -> list[int]:
        """Every docket_id mentioned anywhere in the store, sorted ascending.

        Includes both the ``dockets`` table and every child table — a child
        row whose parent ``dockets`` row never landed (sync interrupted
        between the entry write and the docket meta upsert) is still an
        orphan we want ``prune`` to surface and remove.
        """
        ids: set[int] = set()
        for table in self._DOCKET_TABLES:
            for row in self.conn.execute(
                f"SELECT DISTINCT docket_id FROM {table} WHERE docket_id IS NOT NULL"
            ):
                ids.add(int(row["docket_id"]))
        return sorted(ids)

    def count_docket_rows(self, docket_id: int) -> dict[str, int]:
        """Per-table row count for a single docket — feeds the ``prune`` preview."""
        counts: dict[str, int] = {}
        for table in self._DOCKET_TABLES:
            row = self.conn.execute(
                f"SELECT COUNT(*) AS n FROM {table} WHERE docket_id=?",
                (docket_id,),
            ).fetchone()
            counts[table] = int(row["n"])
        return counts

    def delete_docket(self, docket_id: int) -> dict[str, int]:
        """Cascade-delete every row tied to a docket_id. Returns per-table counts.

        Caller is responsible for backing up the DB first — there are no
        FOREIGN KEY constraints, so this is the only delete path.
        """
        counts: dict[str, int] = {}
        with self.tx():
            for table in self._DOCKET_TABLES:
                cur = self.conn.execute(
                    f"DELETE FROM {table} WHERE docket_id=?",
                    (docket_id,),
                )
                counts[table] = cur.rowcount
        return counts
